server:
  port: 12100
  shutdown: graceful
  forward-headers-strategy: framework

### technical configurations ###
management:
  # for security, don't use same port as application
  server.port: 12101
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health:
      show-details: always
      probes.enabled: true
      group:
        readiness.include: readinessState,diskSpace,rest
        liveness.include: livenessState
  endpoints.web.exposure.include: '*'
  # activate percentiles for web and grpc requests
  metrics.distribution.percentiles-histogram:
    grpc.server.processing.duration: true
    http.server.requests: true

spring:
  cloud:
    config:
      name: timetable
  main:
    banner-mode: off
  profiles:
    default: dev
  data.mongodb:
    uri: ${MONGODB_CONNECTION_STRING}
    auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:https://id.2martens.de}/realms/${KEYCLOAK_REALM:2martens}/protocol/openid-connect/certs
  application:
    name: timetable

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: true
    path: '/timetable/v1/doc/'
  default-produces-media-type: 'application/json'
  api-docs:
    path: '/timetable/v1/api-docs'

openapi:
  description: |
    Open API Documentation for the Timetable API
    
    TODO
    
    
    ## Changelog

    |Version | Change                                 | Author | Date       |
    | ------ | -------------------------------------- | ------ | ---------- |
    | 1.0    | added API Versioning (and changelog)   | Jim    | 13.07.2023 |

  version: 1.0
  title: 'Timetable API'

resttemplate:
  timeout:
    readTimeoutRestHealthIndicatorInMillis: 5000
    connectionRestHealthIndicatorTimeoutInMillis: 5000
    readTimeoutRestTemplateInMillis: 5000
    connectionRestTemplateTimeoutInMillis: 5000

de.twomartens.timetable:
  bahn-api:
    client-id: ${DB_CLIENT_ID}
    client-secret: ${DB_CLIENT_SECRET}

time:
  defaultTimeZone: Europe/Berlin
