name: Docker image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  jib:
    name: Create and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          cache-read-only: true
      - name: Create and publish docker image
        run: ./gradlew -Prelease.useLastTag=true final jib
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
